### PR TITLE
Feat/api

### PR DESCRIPTION
**Pull request by tremarkley**
@davidseid  if you could take a look at my pull request when you get a chance that would be awesome. This pull request includes all the code for setting up my api and database controller

### CODE REVIEW

**Comment by tremarkley** [comment]
[Setup testing framework using Jest](https://trello.com/c/F8BEftfm/8-setup-testing-framework-using-jest)

**Comment by tremarkley** [comment]
[Build out reservations controller to grab and modify reservations data in the database](https://trello.com/c/3Z6ifig0/13-build-out-reservations-controller-to-grab-and-modify-reservations-data-in-the-database)

**Comment by tremarkley** [comment]
[Build Express Server](https://trello.com/c/7H7JizSc/5-build-express-server)

**Comment by tremarkley** [comment]
[Build API to retrieve data from the db](https://trello.com/c/UnbUl90V/6-build-api-to-retrieve-data-from-the-db)

**Comment by tremarkley** [comment]
[Setup express router](https://trello.com/c/06t7Jf2l/12-setup-express-router)

**Comment by davidseid** [comment]
@tremarkley - Hey Harry, this looks awesome, very clean with good separation of concerns. Appreciate the brief explanatory comments in the controller reservations.js file, too. Only thing that caught my eye was the separation of your app.js and server.js files in the server folder. At first I thought it seemed unnecessary since your server file wasn't doing much, but then I saw your commit saying it was so you could test each file separately. More of a question than a suggestion, but is that necessary? Curious if there is a testing convention there I'm not aware of.

Super solid, looks like you have good server and db tests and like your use of destructuring, promises, and request params too. Also was my first time coming across supertest, will look into that for myself. Great work, learning a lot teaming with you.

**Comment by tremarkley** [comment]
@davidseid thanks for the great feedback! The reason I separated those is because supertest takes in an instance of express in order for it to make requests. Therefore, my app.js is an instance of my server that can be imported into my testing library. This allows me to keep my server running on a seperate port while it is being tested. I did not come up with this on my own, but just noticed it on a couple blogs: http://www.albertgao.xyz/2017/05/24/how-to-test-expressjs-with-jest-and-supertest/ https://www.codementor.io/knownasilya/testing-express-apis-with-supertest-du107mcv2

**Pull request merged**
