### PR TITLE
Feat/calendar component

### PR DESCRIPTION
**Pull request by tremarkley**

### CODE REVIEW

**Comment by tremarkley** [comment]
[Integrate a calendar with the dialog for easy selection of dates](https://trello.com/c/zPpLqI3R/17-integrate-a-calendar-with-the-dialog-for-easy-selection-of-dates)

**Comment by tremarkley** [comment]
[As a user, I would like to be able to book a listing over a specified date](https://trello.com/c/UxzzmI1S/15-as-a-user-i-would-like-to-be-able-to-book-a-listing-over-a-specified-date)

**Comment by tremarkley** [comment]
[As a user, I would like to be able to book a listing over a specified date](https://trello.com/c/UxzzmI1S/15-as-a-user-i-would-like-to-be-able-to-book-a-listing-over-a-specified-date)

**Comment by tremarkley** [comment]
[As a user, I would like to be able to book a listing over a specified date](https://trello.com/c/UxzzmI1S/15-as-a-user-i-would-like-to-be-able-to-book-a-listing-over-a-specified-date)

**Comment by tremarkley** [comment]
[As a user, I would like to be able to view what dates a listing is available](https://trello.com/c/UlClWnpD/14-as-a-user-i-would-like-to-be-able-to-view-what-dates-a-listing-is-available)

**Comment by tremarkley** [comment]
[As a user, I would like to be able to view what dates a listing is available](https://trello.com/c/UlClWnpD/14-as-a-user-i-would-like-to-be-able-to-view-what-dates-a-listing-is-available)

**Comment by tremarkley** [comment]
[As a user, I would like to be able to view what dates a listing is available](https://trello.com/c/UlClWnpD/14-as-a-user-i-would-like-to-be-able-to-view-what-dates-a-listing-is-available)

**Comment by tremarkley** [comment]
[After selecting check in date make all dates before it greyed out if check out is active](https://trello.com/c/0arKXfRq/18-after-selecting-check-in-date-make-all-dates-before-it-greyed-out-if-check-out-is-active)

**Comment by tremarkley** [comment]
[Get clear dates button working](https://trello.com/c/SEEOG9Zk/20-get-clear-dates-button-working)

**Comment by tremarkley** [comment]
[When two dates are selected automatically close calendar](https://trello.com/c/o48GI0bH/19-when-two-dates-are-selected-automatically-close-calendar)

**Comment by tremarkley** [comment]
[When two dates are selected automatically close calendar](https://trello.com/c/o48GI0bH/19-when-two-dates-are-selected-automatically-close-calendar)

**Comment by tremarkley** [comment]
[When two dates are selected automatically close calendar](https://trello.com/c/o48GI0bH/19-when-two-dates-are-selected-automatically-close-calendar)

**Comment by tremarkley** [comment]
@davidseid here's my pull request when you have the chance, thanks!

**Comment by davidseid** [comment]
@tremarkley -- Harry, this looks great. I gave the whole thing a first look and then went through the app.jsx and calendar.jsx components in more detail. Didn't see anything I would change really, though I did have a little trouble following what was happening your updateReservationData function. I'm not too familiar with using setState and just passing in a callback, and also how on line 45 the object returned contains a lastPossibleCheckoutDate property without a defined value. I'm sure if I'm quite reading that right, but just wanted to draw your attention to it since I wasn't quite able to follow it.

**Pull request merged**
